### PR TITLE
fix(addon): decouple addon with provider

### LINKED ISSUE #1540: 【Addon】monitor work in kubernetes 1.21/containerd
**What would you like to be added**:

monitor work in kubernetes 1.21/containerd

**Why is this needed**:

### PR DESCRIPTION
**Pull request by TomatoAres**
**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1540 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/platform/util/addon/client.go [hunk 1]
```diff
@@ -0,0 +1,185 @@
+/*
+ * Tencent is pleased to support the open source community by making TKEStack
+ * available.
+ *
+ * Copyright (C) 2012-2019 Tencent. All Rights Reserved.
```
Comment (leoryu) [inline pkg/platform/util/addon/client.go:5]: should be -2021
