### PR TITLE
fix(platform): compatible webhook's certificate and private key

### LINKED ISSUE #886: web hook crt and key should handle upgrade case
**What happened**:

1. introduce by https://github.com/tkestack/tke/pull/829, we should handle tke-platform upgrade case that hook crt and key file not exist
2. please add some comments in you code to clarify the logic, we will remove the logic in future once we don't support old k8s 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- TKE version:
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

### PR DESCRIPTION
**Pull request by wangao1236**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #886 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/platform/provider/baremetal/phases/authzwebhook/authzwebhook.go [hunk 1]
```diff
@@ -58,11 +59,35 @@ type Option struct {
 	IsGlobalCluster      bool
 }
 
+// WebhookCertAndKeyExist checks whether the certificate and private key exist,
+// for compatibility with old version clusters' webhook certificates and private keys.
```
Comment (huxiaoliang) [inline pkg/platform/provider/baremetal/phases/authzwebhook/authzwebhook.go:63]: please highlight this is involved for tke1.5 and will get removed from tke1.6 or future
