### PR TITLE
fix(installer, registry): add s3 storage backend for registry

### LINKED ISSUE #1437: Support s3 as registry's backend
**What would you like to be added**:
Support s3 as registry's backend

**Why is this needed**:
tke-registry-api use local filesystem as default storage backend by default. This will break 3 nodes HA. I found tke-registry-api supports s3 as storage backend already. Add a configuration entry in tke-installer to enable s3 as registry's storage backend would be perfect.

### PR DESCRIPTION
**Pull request by xiaosuiba**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Add s3 storage option for registry. Now users can choose to use s3 as distribution's backend in intaller's configuration.

**Which issue(s) this PR fixes**:

Fixes #1437

**Special notes for your reviewer**:
If a user choose s3 as registry backend, currently only docker images will be saved in the choosing storage as charts are stored in etcd by default. 

**Does this PR introduce a user-facing change?**:
NONE
```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: cmd/tke-installer/app/installer/types/types.go [hunk 1]
```diff
@@ -32,6 +32,13 @@ type CreateClusterPara struct {
 	Config  Config     `json:"Config"`
 }
 
+func (c *CreateClusterPara) RegistryIP() string {
+	if c.Config.HA != nil {
+		return c.Config.HA.VIP()
```
Comment (leoryu) [inline cmd/tke-installer/app/installer/types/types.go:37]: Use VIP have some problem, for local storage case, data of registry is in master0 node, but VIP backend could be master0, master1, master2....

So RegistryIP shouldn't use VIP.

Comment (xiaosuiba) [reply cmd/tke-installer/app/installer/types/types.go:37]: Currently we visit registy-api through tke-gateway, which is a daemonset. Based on this thought I think we could reach registry-api through any gateway running in the cluster, not only the one in master0. 
If there're some case we should visit tke-registry directly, please let me know.

Comment (leoryu) [reply cmd/tke-installer/app/installer/types/types.go:37]: You are right. I forget tke-gateway listen 80/443 for registry.
